name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Start server
      run: |
        cd backend
        nohup python app.py &
    - name: Debug
      run: |
        sleep 5  # Aguarde um tempo para o servidor iniciar
        curl http://localhost:5000  # Substitua pela porta correta
